# 이름 짓기
name: Github Actions 연습하기
# 언제 실행할꺼야?
on:
  push:
    branches:
      - feature/*

# 뭘 실행할꺼야? -> 직업 부여
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 불러오기
        uses: actions/checkout@v5

      - name: Node.js 설치
        uses: actions/setup-node@v6
        # 옵션: 노드 24 버전을 설치해
        with:
          node-version: "24"

      - name: 의존성 설치
        run: npm ci

      - name: 테스트 실행
        run: npm run test
